### PR TITLE
Change SUIT_Parameters being optional in system-property-claims

### PR DESCRIPTION
**Pull request by mcd500**

### CODE REVIEW

**Comment by mcd500** [comment]
This PR will allow the system-property-claims in SUIT_Report for the TEEP Protocol to have no SUIT_Parameters.

It is discussed at the issue in TEEP Protocol.
https://github.com/ietf-teep/teep-protocol/issues/291

I closed the PR https://github.com/bremoran/suit-report/pull/3 
which was made to github.com/bremoran/suit-report.

**Comment by mcd500** [comment]
The Query-Response in TEEP Message uses system-property-claims in tc-list to inform which TCs are already installed in the TEEP Agent to the TAM.
The current TEEP Protocol draft only using system-component-id in the system-property-claims with no SUIT_Parameters.

This is the link to the example of Query-Response which has the system-property-claims in tc-list.
https://github.com/ietf-teep/teep-protocol/blob/master/cbor/query_response.diag.txt#L11-L16

This is the link to the description of the tc-list in Query-Response.
https://github.com/ietf-teep/teep-protocol/blob/master/draft-ietf-teep-protocol.md#queryresponse-message-query-response

Maybe should add SUIT_Parameters in the system-property-claims of the tc-list here?

**Comment by bremoran** [comment]
Is the component ID meaningful at all without a measurement of the content of the component ID? It seems to me that there's entirely too much trust in the TEE if a component ID alone is good enough. What's the reasoning for leaving the digest out?

**Comment by mcd500** [comment]
@bremoran 
I talked to Ken. 
This PR could be closed.

In the example of QueryResponse in TEEP protocol,
https://github.com/ietf-teep/teep-protocol/blob/master/cbor/query_response.diag.txt#L11-L16
two TCs are listed in the tc-list.
Will update the example to have one of the TC in the tc-list to have component ID supplied with version information as a SUIT_Parameters and another TC having component ID and digest value as a SUIT_Parameters.
So system-property-claims having at least one SUIT_Parameters in the system-property-claims is perfectly fine.

**Comment by mcd500** [comment]
The PR at TEEP Protocol for this issue were merged.
https://github.com/ietf-teep/teep-protocol/pull/306

**Pull request closed without merging**
